# Enforce TLS connections using SCRAM authentication
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     peer
hostssl all             all             all                     scram-sha-256
